import flagItaly from "../assets/image/flags/italy.png";
import flagArgentina from "../assets/image/flags/argentina.png";
import flagChina from "../assets/image/flags/china.png";
import flagUSA from "../assets/image/flags/usa.png";

const database = {
  foods: [
    {
      id: 1,
      name: "Spiedini",
      type: "Appetizer",
      origin: "Italy",
      flag: { flagItaly },
      image: "../assets/image/food/spiedini.jpg",
      alt: "Italian Spiedini",
      ingredients: [
        "Beef",
        "Chicken",
        "Pork",
        "2 - 5 Bell Peppers",
        "2 - 5 Onions",
        "Zucchini",
        "Basil",
        "Bay Leaves",
        "Mushrooms",
        "Squash",
      ],
      preparation: [
        "Cut the meat and vegetables into small pieces. ",
        "Place the meat and vegetables onto skewers.",
        "Grill the skewers over medium-high heat for 8-10 minutes.",
        "Turn the skewers every few minutes to prevent burning.",
        "Marinade and serve with sauce",
      ],
      ytID: "5gmJBgQS0bs",
    },
    {
      id: 2,
      name: "Mooncake",
      type: "Dessert",
      origin: "China",
      flag: { flagChina },
      image: "../assets/image/food/mooncake.jpg",
      alt: "Chinese Mooncake",
      inredients: [
        "250 gram flour",
        "100 gram golden syrup",
        "50 gram vegetable oil",
        "250 gram lotus paste",
        "1 salted egg-yolk",
      ],
      preparation: [
        "Mix the flour, golden syrup, vegetable oil, and lye water in a bowl to form a smooth dough.",
        "Wrap the dough in plastic wrap and let it rest for 30 minutes.",
        "Divide the lotus seed paste into small balls of equal size.",
        "Divide the dough into small pieces of equal size and flatten them into circles.",
        "Place a ball of lotus seed paste in the center of each circle of dough and wrap the dough around it, making sure there are no cracks.",
        "Press a salted egg yolk into the center of each mooncake.",
        "Place the mooncakes into mooncake molds and press them down firmly.",
        "Bake the mooncakes in a preheated oven at 350°F (180°C) for 10 minutes.",
        "Remove the mooncakes from the oven and let them cool for 10 minutes.",
        "Brush the mooncakes with egg wash and return them to the oven.",
        "Bake the mooncakes for an additional 10-15 minutes, or until golden brown.",
        "Remove the mooncakes from the oven and let them cool completely before serving.",
      ],
      ytID: "2VJ9fMzl8gE",
    },
    {
      id: 3,
      name: "Buffalo Wings",
      type: "Appetizer",
      origin: "United States",
      flag: { flagUSA },
      image: "../assets/image/food/buffalowings.jpg",
      alt: "American Buffalo Wings",
      ingredients: [
        "1 kg chicken wings",
        "1/2 cup all-purpose flour",
        "1/2 tsp paprika",
        "1/2 tsp cayenne pepper",
        "1/4 tsp garlic powder",
        "1/4 tsp salt",
        "1/4 tsp black pepper",
        "1/4 cup unsalted butter",
        "1/4 cup hot sauce",
        "1 tbsp honey",
        "1 tbsp Worcestershire sauce",
        "1 tbsp apple cider vinegar",
      ],
      preparation: [
        "Preheat oven to 200°C (400°F).",
        "Line a baking sheet with parchment paper.",
        "In a bowl, mix the flour, paprika, cayenne pepper, garlic powder, salt, and black pepper.",
        "Dredge the chicken wings in the flour mixture, shaking off any excess.",
        "Place the chicken wings on the prepared baking sheet and bake for 25-30 minutes, or until crispy and golden brown.",
        "In a saucepan, melt the butter over low heat.",
        "Add the hot sauce, honey, Worcestershire sauce, and apple cider vinegar to the melted butter and stir to combine.",
        "Increase the heat to medium and bring the sauce to a simmer.",
        "Simmer the sauce for 5-10 minutes, or until slightly thickened.",
        "Toss the baked chicken wings in the buffalo sauce until coated.",
        "Serve immediately with celery sticks and blue cheese dressing, if desired.",
      ],
      ytID: "zKtPIgPvREc",
    },
    {
      id: 4,
      name: "Panna Cotta",
      type: "Dessert",
      origin: "Italy",
      flag: { flagItaly },
      image: "../assets/image/food/pannacotta.jpg",
      alt: "Italian Panna Cotta",
      ingredients: [
        "500 ml heavy cream",
        "50 g granulated sugar",
        "1 vanilla bean, split and scraped",
        "2 tsp powdered gelatin",
        "2 tbsp cold water",
      ],
      preparation: [
        "In a saucepan, combine the heavy cream, sugar, and vanilla bean and seeds.",
        "Bring the mixture to a simmer over medium heat, stirring occasionally.",
        "Remove the saucepan from the heat.",
        "In a small bowl, sprinkle the gelatin over the cold water and let stand for 5 minutes.",
        "Whisk the gelatin mixture into the warm cream mixture until fully dissolved.",
        "Remove the vanilla bean from the mixture.",
        "Divide the mixture evenly among 4-6 ramekins or small glasses.",
        "Cover each ramekin or glass with plastic wrap and refrigerate for at least 4 hours, or until set.",
        "To serve, dip the ramekins or glasses into warm water for a few seconds, then invert onto a plate to release the panna cotta.",
      ],
      ytID: "jKAr1rgZdEI",
    },
    {
      id: 5,
      name: "Puchero",
      type: "Main Course",
      origin: "Argentina",
      flag: { flagArgentina },
      image: "../assets/image/food/puchero.jpg",
      alt: "Argentinian Puchero",
      ingredients: [
        "2 lb beef brisket",
        "2 lb bone-in chicken thighs",
        "4 cups beef broth",
        "4 cups water",
        "2 onions, peeled and halved",
        "4 carrots, peeled and chopped",
        "4 potatoes, peeled and chopped",
        "1 sweet potato, peeled and chopped",
        "1/2 butternut squash, peeled and chopped",
        "1 cup cooked chickpeas",
        "1 tbsp paprika",
        "1 tbsp dried oregano",
        "1 bay leaf",
        "Salt and black pepper, to taste",
      ],
      preparation: [
        "In a large pot, bring the beef broth and water to a boil.",
        "Add the beef brisket and chicken thighs, and simmer for 10 minutes.",
        "Add the onions, carrots, potatoes, sweet potato, butternut squash, chickpeas, paprika, oregano, bay leaf, salt, and black pepper.",
        "Bring the mixture to a boil, then reduce the heat and simmer for 1-2 hours, or until the meat is tender and the vegetables are cooked through.",
        "Remove the meat from the pot and shred it.",
        "Serve the puchero in bowls, with the meat and vegetables arranged on top.",
      ],
      ytID: "Ie5b5LJdKDI",
    },
    {
      id: 6,
      name: "Vegetable Pie",
      type: "Main Course",
      origin: "United States",
      flag: { flagUSA },
      image: "../assets/image/food/vegetablepie.jpg",
      alt: "American Vegetable Pie",
      ingredients: [
        "1 9-inch pie crust, unbaked",
        "1 cup chopped onion",
        "1 cup chopped bell pepper",
        "1 cup chopped mushrooms",
        "1 cup chopped zucchini",
        "1 cup chopped yellow squash",
        "1 cup fresh or frozen corn",
        "2 cloves garlic, minced",
        "1 tsp dried basil",
        "1 tsp dried oregano",
        "1/2 tsp dried thyme",
        "1/4 tsp cayenne pepper",
        "Salt and black pepper, to taste",
        "4 eggs",
        "1/2 cup milk",
        "1/2 cup sour cream",
        "1 cup shredded cheddar cheese",
      ],
      preparation: [
        "Preheat the oven to 375°F (190°C).",
        "In a large skillet, sauté the onion, bell pepper, mushrooms, zucchini, and yellow squash until tender.",
        "Add the corn, garlic, basil, oregano, thyme, cayenne pepper, salt, and black pepper, and sauté for another 2-3 minutes.",
        "In a mixing bowl, whisk together the eggs, milk, and sour cream.",
        "Stir in the sautéed vegetables and shredded cheddar cheese.",
        "Pour the mixture into the unbaked pie crust.",
        "Bake for 40-45 minutes, or until the filling is set and the crust is golden brown.",
        "Let the pie cool for a few minutes before slicing and serving.",
      ],
      ytID: "w5O5wkSx8OY",
    },
    {
      id: 7,
      name: "Durian Roll",
      type: "Dessert",
      origin: "China",
      flag: { flagChina },
      image: "../assets/image/food/frieddurian.jpg",
      alt: "Chinese Durian Rolls",
      ingredients: [
        "1 cup durian flesh, pureed",
        "1/2 cup whipping cream",
        "1/4 cup sugar",
        "1/4 tsp salt",
        "12 egg roll wrappers",
        "1/4 cup melted butter",
        "1/4 cup honey",
        "1/4 cup chopped roasted peanuts",
      ],
      preparation: [
        "In a mixing bowl, whisk together the durian puree, whipping cream, sugar, and salt until smooth and creamy.",
        "Place an egg roll wrapper on a clean work surface, with one corner facing you.",
        "Spoon about 2 tablespoons of the durian filling onto the bottom third of the wrapper, leaving about 1 inch of space on either side.",
        "Fold the bottom corner up over the filling, then fold the sides in towards the center, like an envelope.",
        "Roll the wrapper up tightly, pressing the edges to seal.",
        "Repeat with the remaining wrappers and filling.",
        "Preheat the oven to 350°F (175°C).",
        "Brush the rolls with melted butter, and bake for 10-15 minutes, until golden brown and crispy.",
        "Drizzle with honey and sprinkle with chopped roasted peanuts before serving.",
      ],
      ytID: "7GgBwDpaLe4",
    },
    {
      id: 8,
      name: "Provoleta",
      type: "Appetizer",
      origin: "Argentina",
      flag: { flagArgentina },
      image: "../assets/image/food/provoleta.jpg",
      alt: "Argentinian Provoleta",
      ingredients: [
        "1 wheel provoleta cheese",
        "1 tbsp olive oil",
        "1/2 tbsp dried oregano",
        "1/2 tbsp red pepper flakes",
        "1/2 tbsp smoked paprika",
        "1/2 tbsp garlic powder",
        "1/2 tbsp salt",
        "1/2 tbsp black pepper",
        "Lemon wedges, to serve",
        "Crusty bread, to serve",
      ],
      preparation: [
        "Preheat a grill or grill pan over high heat.",
        "Brush the provoleta cheese with olive oil on both sides.",
        "In a small bowl, mix together the oregano, red pepper flakes, smoked paprika, garlic powder, salt, and black pepper.",
        "Sprinkle the spice mixture over the cheese.",
        "Place the cheese on the grill and cook for about 2-3 minutes per side, until golden and slightly charred.",
        "Serve hot with lemon wedges and crusty bread.",
      ],
      ytID: "AmH7VMyxKWo",
    },
    {
      id: 9,
      name: "Peanut Butter Brownies",
      type: "Dessert",
      origin: "United States",
      flag: { flagUSA },
      image: "../assets/image/food/brownies.jpg",
      alt: "American Peanut Butter Brownies",
      ingredients: [
        "1/2 cup unsalted butter, melted",
        "1/2 cup creamy peanut butter",
        "1 cup granulated sugar",
        "1/2 cup all-purpose flour",
        "1/2 cup cocoa powder",
        "1/4 teaspoon salt",
        "2 large eggs",
        "1 teaspoon vanilla extract",
        "1/2 cup semisweet chocolate chips",
      ],
      preparation: [
        "Preheat the oven to 350°F. Line an 8-inch square baking pan with parchment paper.",
        "In a large mixing bowl, whisk together the melted butter, peanut butter, and sugar until smooth.",
        "Add the flour, cocoa powder, and salt, and stir until well combined.",
        "Add the eggs and vanilla extract, and stir until the batter is smooth.",
        "Fold in the chocolate chips.",
        "Pour the batter into the prepared pan and smooth out the top.",
        "Bake for 25-30 minutes, or until a toothpick inserted into the center comes out clean.",
        "Remove from the oven and let cool in the pan for at least 15 minutes before slicing and serving.",
      ],
      ytID: "vE1NlXKfA3k",
    },
    {
      id: 10,
      name: "Brasato",
      type: "Main Course",
      origin: "Italy",
      flag: { flagItaly },
      image: "../assets/image/food/brasato.jpg",
      alt: "Italian Brasato",
      ingredients: [
        "2 pounds beef chuck roast",
        "2 tablespoons olive oil",
        "1 onion, chopped",
        "2 carrots, peeled and chopped",
        "2 celery stalks, chopped",
        "3 garlic cloves, minced",
        "1 cup dry red wine",
        "1 can (14.5 oz) diced tomatoes",
        "2 cups beef broth",
        "2 bay leaves",
        "1 teaspoon dried thyme",
        "1 teaspoon dried rosemary",
        "Salt and pepper, to taste",
      ],
      preparation: [
        "Preheat oven to 325°F.",
        "Heat olive oil in a large Dutch oven over medium-high heat.",
        "Season the beef chuck roast with salt and pepper on both sides.",
        "Sear the beef chuck roast until browned on both sides, about 4-5 minutes per side.",
        "Remove the beef chuck roast from the Dutch oven and set aside.",
        "Add onion, carrots, celery, and garlic to the Dutch oven and cook until softened, about 5-7 minutes.",
        "Add red wine and stir to scrape up any browned bits from the bottom of the Dutch oven.",
        "Add diced tomatoes, beef broth, bay leaves, thyme, and rosemary. Stir to combine.",
        "Add the beef chuck roast back to the Dutch oven and spoon some of the vegetable mixture over the top of the roast.",
        "Cover the Dutch oven and transfer to the oven. Cook for 2 1/2 to 3 hours, or until the beef chuck roast is tender.",
        "Remove the beef chuck roast from the Dutch oven and let it rest for a few minutes.",
        "Using an immersion blender, puree the vegetables and cooking liquid until smooth.",
        "Slice the beef chuck roast against the grain and serve with the vegetable sauce.",
      ],
      ytID: "g1mwvIK8q3E",
    },
  ],
};

export default database;
